// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzE13IwlF4CGpDPzmIPbMNf4SFcYqhrwA',
    appId: '1:228298539474:web:9681c6db7a2073d02f480b',
    messagingSenderId: '228298539474',
    projectId: 'firstflutter-3eefc',
    authDomain: 'firstflutter-3eefc.firebaseapp.com',
    storageBucket: 'firstflutter-3eefc.firebasestorage.app',
    measurementId: 'G-M2VYNRRX34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARu435NCD_GFf72x2NindwolSSONxzvR8',
    appId: '1:228298539474:android:471b356dc757e8e12f480b',
    messagingSenderId: '228298539474',
    projectId: 'firstflutter-3eefc',
    storageBucket: 'firstflutter-3eefc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyButQa3s94TzX0FpSGWP7twxOIMgBjp3bE',
    appId: '1:228298539474:ios:c844748157e0ac7a2f480b',
    messagingSenderId: '228298539474',
    projectId: 'firstflutter-3eefc',
    storageBucket: 'firstflutter-3eefc.firebasestorage.app',
    iosBundleId: 'com.example.firstflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyButQa3s94TzX0FpSGWP7twxOIMgBjp3bE',
    appId: '1:228298539474:ios:c844748157e0ac7a2f480b',
    messagingSenderId: '228298539474',
    projectId: 'firstflutter-3eefc',
    storageBucket: 'firstflutter-3eefc.firebasestorage.app',
    iosBundleId: 'com.example.firstflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzE13IwlF4CGpDPzmIPbMNf4SFcYqhrwA',
    appId: '1:228298539474:web:092d2327b847f5a12f480b',
    messagingSenderId: '228298539474',
    projectId: 'firstflutter-3eefc',
    authDomain: 'firstflutter-3eefc.firebaseapp.com',
    storageBucket: 'firstflutter-3eefc.firebasestorage.app',
    measurementId: 'G-SB7711BSGD',
  );

}